data_prep:
  bucket: jb-s3-bucket
  prefix: nfl_plays/
  file_type: png
  teams: 
    - 49ers
    - bears
    - bengals
    - bills
    - broncos
    - browns
    - buccaneers 
    - cardinals 
    - chargers 
    - chiefs 
    - colts 
    - cowboys 
    - dolphins 
    - eagles 
    - falcons 
    - giants 
    - jaguars 
    - jets 
    - lions 
    - packers 
    - panthers 
    - patriots 
    - raiders 
    - rams 
    - ravens 
    - redskins 
    - saints 
    - seahawks 
    - steelers 
    - texans 
    - titans 
    - vikings
  output_dir: image_data
  full_image_path: full_images.npy
  sample_image_path: sample_data.npy
  full_image_norm_path: full_images_255.npy
  shape:
    - 160
    - 350
    - 4
neural_net:
  vae:
    latent_vector_dim: 200
    recon_weight: 1
    kld_weight: 100
    test_size: 0.2
    batch_size: 128
    epochs: 500
    no_cuda: True
    seed: 1
    log_interval: 10
  cvae:
    latent_vector_dim: 300
    recon_weight: 1
    kld_weight: 100
    test_size: 0.2
    batch_size: 128
    epochs: 500
    no_cuda: True
    seed: 1
    log_interval: 10
  dcgan:
    latent_vector_dim: 300
    test_size: 0.2
    batch_size: 128
    epochs: 500
    no_cuda: True
    seed: 1
    log_interval: 10